In [3]:
import chess
import numpy as np

# Create a chess board object
board = chess.Board()

# Define the dimensions of the chessboard
rows = 8
cols = 8

# Create an empty 3D array with shape (rows, cols, 6)
chessboard = np.zeros((rows, cols, 6), dtype=np.int8)

# Map piece types to layer indices
piece_to_layer = {'p': 0, 'n': 1, 'b': 2, 'r': 3, 'q': 4, 'k': 5}

# Populate the chessboard array with the initial positions
for square in chess.SQUARES:
    print(square)
    if board.piece_at(square):
        piece = board.piece_at(square).symbol().lower()
        layer = piece_to_layer[piece]
        piece_value = -1 if piece.islower() else 1
        rank, file = chess.square_rank(square), chess.square_file(square)
        chessboard[rank, file, layer] = piece_value

# Print the chessboard array
print(chessboard)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
[[[ 0  0  0 -1  0  0]
  [ 0 -1  0  0  0  0]
  [ 0  0 -1  0  0  0]
  [ 0  0  0  0 -1  0]
  [ 0  0  0  0  0 -1]
  [ 0  0 -1  0  0  0]
  [ 0 -1  0  0  0  0]
  [ 0  0  0 -1  0  0]]

 [[-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]
  [-1  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0 

In [5]:
import re
import chess
import numpy as np

letter_to_number = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7}
number_to_letter = {0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h'}

def layer_to_array(board, piece):
    fen = board.fen().split()[0]
    fen = re.sub(f'[^{piece}{piece.upper()}]', '.', fen)
    fen = re.sub(f'{piece}', '-1', fen)
    fen = re.sub(f'{piece.upper()}', '1', fen)
    fen = re.sub(f'/', '', fen)
    board_array = np.array(list(fen))
    return board_array.reshape(8, 8).astype(int)

def moves_to_array(board):
    moves = np.zeros((64), dtype=int)
    for move in board.legal_moves:
        from_square = move.from_square
        to_square = move.to_square
        moves[from_square] = 1
        moves[to_square] = 1
    return moves.reshape(8, 8)

def board_to_array(board):
    pieces = ['p', 'n', 'b', 'r', 'q', 'k']
    layers = []
    for piece in pieces:
        layer = layer_to_array(board, piece)
        layers.append(layer)
    moves = moves_to_array(board)
    layers.append(moves)
    board_array = np.stack(layers)
    return board_array

# Create a chess board and convert it to a 3D matrix with moves
board = chess.Board()
board_array = board_to_array(board)
print(board_array)


ValueError: cannot reshape array of size 51 into shape (8,8)

In [6]:
import numpy as np

# Create a 8x8x12 NumPy array
bitboard = np.zeros((8, 8, 12), dtype=np.uint64)

# Define the bitboard representation of the default chess starting position
bitboard[6, :, 0] = 0b11111111  # White Pawns
bitboard[7, [0, 7], 1] = 0b1  # White Knights
bitboard[7, [1, 6], 2] = 0b1  # White Bishops
bitboard[7, [2, 5], 3] = 0b1  # White Rooks
bitboard[7, 3, 4] = 0b1  # White Queen
bitboard[7, 4, 5] = 0b1  # White King

bitboard[1, :, 6] = 0b11111111  # Black Pawns
bitboard[0, [0, 7], 7] = 0b1  # Black Knights
bitboard[0, [1, 6], 8] = 0b1  # Black Bishops
bitboard[0, [2, 5], 9] = 0b1  # Black Rooks
bitboard[0, 3, 10] = 0b1  # Black Queen
bitboard[0, 4, 11] = 0b1  # Black King

# Print the bitboard representation
for i in range(12):
    print(f'Piece {i+1}:')
    print(bitboard[..., i])
    print()

Piece 1:
[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [255 255 255 255 255 255 255 255]
 [  0   0   0   0   0   0   0   0]]

Piece 2:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]]

Piece 3:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0]]

Piece 4:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0]]

Piece 5:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]

Piece 6:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [45]:
import chess

board = chess.Board()
board.push_san('Nf3')
board.castling_rights
print(chess.Bitboard(fen=chess.STARTING_BOARD_FEN))



TypeError: 'fen' is an invalid keyword argument for int()

In [35]:
board.ep_square

In [36]:
board.pseudo_legal_moves

<PseudoLegalMoveGenerator at 0x11198bcd0 (Nh6, Nf6, Nc6, Na6, h6, g6, f6, e6, d6, c6, b6, a6, h5, g5, f5, e5, d5, c5, b5, a5)>

In [37]:
board.peek()

Move.from_uci('g1f3')

In [38]:
board.fen()

'rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R b KQkq - 1 1'

In [41]:
board.status()

<Status.VALID: 0>

In [51]:
board.fen()

'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1'

In [66]:
board.reset_board()

In [64]:
moves = ['e4','Na6', 'e5', 'd5']
for move in moves:
    board.push_san(move)

In [69]:
chess.square_name(board.ep_square)

'e3'

In [67]:
board.push_san('e4')

Move.from_uci('e2e4')